version: '3.8'

networks:
  canonika-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  # Quarter - Ponto de Entrada
  quarter:
    build:
      context: .
      dockerfile: ./quarter/Dockerfile
    container_name: canonika_quarter
    ports:
      - "3700:80"
      - "8000:8000"
      - "5174:5174"
    networks:
      - canonika-network
    environment:
      - DEV_MODE=false
      - QUARTER_URL=http://quarter:80
      - HARBOR_URL=http://harbor:3701
      - GUARDIAN_URL=http://guardian:3705
      - SKIPPER_URL=http://skipper:3702
      - BEACON_URL=http://beacon:3703
      - FISHER_URL=http://fisher:3706
      - TOLLGATE_URL=http://tollgate:3707
      - LEDGER_URL=http://ledger:3708
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
      - OPA_URL=http://opa:8181
      - CLICKHOUSE_URL=http://clickhouse:8123
    depends_on:
      - postgres
      - redis

  # Harbor - Dashboard Principal
  harbor:
    build:
      context: .
      dockerfile: ./harbor/Dockerfile
    container_name: canonika_harbor
    ports:
      - "3701:3701"
      - "8001:8001"
      - "5171:5171"
    networks:
      - canonika-network
    environment:
      - DEV_MODE=true
      - QUARTER_URL=http://quarter:80
      - HARBOR_URL=http://harbor:3701
      - GUARDIAN_URL=http://guardian:3705
      - SKIPPER_URL=http://skipper:3702
      - BEACON_URL=http://beacon:3703
      - FISHER_URL=http://fisher:3706
      - TOLLGATE_URL=http://tollgate:3707
      - LEDGER_URL=http://ledger:3708
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
      - OPA_URL=http://opa:8181
      - CLICKHOUSE_URL=http://clickhouse:8123
    depends_on:
      - quarter
      - postgres

  # Guardian - Segurança
  guardian:
    build: ./guardian
    container_name: canonika_guardian
    ports:
      - "3705:3705"
      - "8005:8005"
      - "5175:5175"
    networks:
      - canonika-network
    environment:
      - DEV_MODE=false
      - QUARTER_URL=http://quarter:80
      - HARBOR_URL=http://harbor:3701
      - GUARDIAN_URL=http://guardian:3705
      - SKIPPER_URL=http://skipper:3702
      - BEACON_URL=http://beacon:3703
      - FISHER_URL=http://fisher:3706
      - TOLLGATE_URL=http://tollgate:3707
      - LEDGER_URL=http://ledger:3708
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
      - OPA_URL=http://opa:8181
      - CLICKHOUSE_URL=http://clickhouse:8123
    depends_on:
      - quarter
      - keycloak
      - opa

  # Skipper - Navegação
  skipper:
    build: ./skipper
    container_name: canonika_skipper
    ports:
      - "3702:3702"
      - "8002:8002"
      - "5172:5172"
    networks:
      - canonika-network
    environment:
      - DEV_MODE=false
      - QUARTER_URL=http://quarter:80
      - HARBOR_URL=http://harbor:3701
      - GUARDIAN_URL=http://guardian:3705
      - SKIPPER_URL=http://skipper:3702
      - BEACON_URL=http://beacon:3703
      - FISHER_URL=http://fisher:3706
      - TOLLGATE_URL=http://tollgate:3707
      - LEDGER_URL=http://ledger:3708
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
      - OPA_URL=http://opa:8181
      - CLICKHOUSE_URL=http://clickhouse:8123
    depends_on:
      - quarter

  # Beacon - Monitoramento
  beacon:
    build:
      context: .
      dockerfile: ./beacon/Dockerfile
    container_name: canonika_beacon
    ports:
      - "3703:3703"
      - "8003:8003"
      - "5173:5173"
    networks:
      - canonika-network
    environment:
      - DEV_MODE=true
      - QUARTER_URL=http://quarter:80
      - HARBOR_URL=http://harbor:3701
      - GUARDIAN_URL=http://guardian:3705
      - SKIPPER_URL=http://skipper:3702
      - BEACON_URL=http://beacon:3703
      - FISHER_URL=http://fisher:3706
      - TOLLGATE_URL=http://tollgate:3707
      - LEDGER_URL=http://ledger:3708
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
      - OPA_URL=http://opa:8181
      - CLICKHOUSE_URL=http://clickhouse:8123
    depends_on:
      - quarter
      - clickhouse

  # Beacon Old - Versão de Referência
  beacon_old:
    build:
      context: .
      dockerfile: ./beacon_old/Dockerfile
    container_name: canonika_beacon_old
    ports:
      - "3799:3799"
      - "8004:8004"
      - "5179:5179"
    networks:
      - canonika-network
    environment:
      - DEV_MODE=true
      - QUARTER_URL=http://quarter:80
      - HARBOR_URL=http://harbor:3701
      - GUARDIAN_URL=http://guardian:3705
      - SKIPPER_URL=http://skipper:3702
      - BEACON_URL=http://beacon:3703
      - BEACON_OLD_URL=http://beacon_old:3799
      - FISHER_URL=http://fisher:3706
      - TOLLGATE_URL=http://tollgate:3707
      - LEDGER_URL=http://ledger:3708
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
      - OPA_URL=http://opa:8181
      - CLICKHOUSE_URL=http://clickhouse:8123
    depends_on:
      - quarter
      - clickhouse

  # Fisher - Coleta de Dados
  fisher:
    build:
      context: .
      dockerfile: ./fisher/Dockerfile
    container_name: canonika_fisher
    ports:
      - "3706:3706"
      - "3707:80"
      - "8006:8006"
      - "5176:5176"
    networks:
      - canonika-network
    environment:
      - DEV_MODE=false
      - QUARTER_URL=http://quarter:80
      - HARBOR_URL=http://harbor:3701
      - GUARDIAN_URL=http://guardian:3705
      - SKIPPER_URL=http://skipper:3702
      - BEACON_URL=http://beacon:3703
      - FISHER_URL=http://fisher:3706
      - TOLLGATE_URL=http://tollgate:3707
      - LEDGER_URL=http://ledger:3708
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
      - OPA_URL=http://opa:8181
      - CLICKHOUSE_URL=http://clickhouse:8123
    depends_on:
      - quarter
      - clickhouse

  # Tollgate - Gateway
  tollgate:
    build: ./tollgate
    container_name: canonika_tollgate
    ports:
      - "3707:3707"
      - "8007:8007"
      - "5177:5177"
    networks:
      - canonika-network
    environment:
      - DEV_MODE=false
      - QUARTER_URL=http://quarter:80
      - HARBOR_URL=http://harbor:3701
      - GUARDIAN_URL=http://guardian:3705
      - SKIPPER_URL=http://skipper:3702
      - BEACON_URL=http://beacon:3703
      - FISHER_URL=http://fisher:3706
      - TOLLGATE_URL=http://tollgate:3707
      - LEDGER_URL=http://ledger:3708
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
      - OPA_URL=http://opa:8181
      - CLICKHOUSE_URL=http://clickhouse:8123
    depends_on:
      - quarter
      - guardian

  # Ledger - Financeiro
  ledger:
    build: ./ledger
    container_name: canonika_ledger
    ports:
      - "3708:3708"
      - "8008:8008"
      - "5178:5178"
    networks:
      - canonika-network
    environment:
      - DEV_MODE=false
      - QUARTER_URL=http://quarter:80
      - HARBOR_URL=http://harbor:3701
      - GUARDIAN_URL=http://guardian:3705
      - SKIPPER_URL=http://skipper:3702
      - BEACON_URL=http://beacon:3703
      - FISHER_URL=http://fisher:3706
      - TOLLGATE_URL=http://tollgate:3707
      - LEDGER_URL=http://ledger:3708
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
      - OPA_URL=http://opa:8181
      - CLICKHOUSE_URL=http://clickhouse:8123
    depends_on:
      - quarter
      - postgres

  # Keycloak - Autenticação
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: canonika_keycloak
    ports:
      - "8080:8080"
    networks:
      - canonika-network
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak123
    command: start-dev
    depends_on:
      - postgres

  # PostgreSQL - Banco Principal
  postgres:
    image: postgres:15-alpine
    container_name: canonika_postgres
    ports:
      - "5432:5432"
    networks:
      - canonika-network
    environment:
      - POSTGRES_DB=canonika
      - POSTGRES_USER=canonika
      - POSTGRES_PASSWORD=canonika123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  # Redis - Cache
  redis:
    image: redis:7-alpine
    container_name: canonika_redis
    ports:
      - "6379:6379"
    networks:
      - canonika-network
    volumes:
      - redis_data:/data

  # OPA - Políticas
  opa:
    image: openpolicyagent/opa:latest
    container_name: canonika_opa
    ports:
      - "8181:8181"
    networks:
      - canonika-network
    command: run --server --addr :8181
    volumes:
      - ./policies:/policies

  # ClickHouse - Analytics
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: canonika_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - canonika-network
    environment:
      - CLICKHOUSE_DB=canonika
      - CLICKHOUSE_USER=canonika
      - CLICKHOUSE_PASSWORD=canonika123
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  # Template - Layout Oficial
  template:
    build:
      context: ./template/api
      dockerfile: Dockerfile
    container_name: canonika_template
    ports:
      - "8015:8015"
    networks:
      - canonika-network
    environment:
      - DATABASE_URL=postgresql://canonika:canonika123@postgres:5432/canonika
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  template-web:
    build:
      context: .
      dockerfile: ./template/web/Dockerfile
    container_name: canonika_template_web
    ports:
      - "3790:80"
    depends_on:
      - template
    networks:
      - canonika-network

volumes:
  postgres_data:
  redis_data:
  clickhouse_data: 