services:
  # Banco de dados principal
  postgres:
    image: postgres:15
    container_name: canonika_postgres
    environment:
      POSTGRES_USER: canonika
      POSTGRES_PASSWORD: canonika
      POSTGRES_DB: canonika
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Cache e filas
  redis:
    image: redis:7
    container_name: canonika_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Microserviços principais para desenvolvimento
  harbor:
    build: ./harbor
    container_name: canonika_harbor
    ports:
      - "3701:80"
    volumes:
      - ./shared/styles:/usr/share/nginx/html/shared/styles
      - ./harbor/web:/usr/share/nginx/html
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  skipper:
    build: ./skipper
    container_name: canonika_skipper
    ports:
      - "3702:80"
    volumes:
      - ./shared/styles:/usr/share/nginx/html/shared/styles
      - ./skipper/web:/usr/share/nginx/html
      - ./skipper/api:/app/api
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  tollgate:
    build: ./tollgate
    container_name: canonika_tollgate
    ports:
      - "3703:80"
    volumes:
      - ./shared/styles:/usr/share/nginx/html/shared/styles
      - ./tollgate/web:/usr/share/nginx/html
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  quarter:
    build: ./quarter
    container_name: canonika_quarter
    ports:
      - "3704:80"
    volumes:
      - ./shared/styles:/usr/share/nginx/html/shared/styles
      - ./quarter/web:/usr/share/nginx/html
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata: 